services:
  mysql:
    image: mysql:8.0.20
    platform: linux/amd64  # Fix for M-series Mac compatibility
    command: mysqld --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: "/usr/bin/mysql --user=$$MYSQL_USER --password=$$MYSQL_PASSWORD --execute \"SELECT 1;\""
      interval: 2s
      timeout: 20s
      retries: 10
    environment:
      - MYSQL_TCP_PORT_3306_TCP=3306
    env_file:
      - ./configuration/mysql.env
    volumes:
      - ${MYSQL_DATA_PATH}:/var/lib/mysql
  app:
    image: app:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_EXTERNAL_PORT}:80"
    environment:
      - APP_HTTP_HOST=0.0.0.0
      - APP_HTTP_PORT=80
      - MYSQL_TCP_PORT=3306
      - MYSQL_HOST=mysql
      - APP_COMPONENT=api
    volumes:
      # FOR DEVELOPMENT ONLY
      - ./app:/app/app:ro
    env_file:
      - ./configuration/app.env
      - ./configuration/mysql.env
    depends_on:
      mysql:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    healthcheck:
      test: "curl --fail http://app/api/v1/health"
      interval: 10s
      timeout: 1s
      retries: 2